server:
  port: 10000

spring:
  application:
    name: eureka-server

#eureka的配置
eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10000/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 100000